
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int como = 31;
  public static final int mayor_o_igual = 21;
  public static final int comentario_multilinea = 9;
  public static final int imprimir = 57;
  public static final int con_parametros = 53;
  public static final int mod = 18;
  public static final int con = 43;
  public static final int hasta = 41;
  public static final int asignacionSimbolo = 11;
  public static final int es_diferente = 24;
  public static final int hasta_que = 49;
  public static final int entonces = 38;
  public static final int fin_funcion = 55;
  public static final int inicio = 28;
  public static final int caracter = 7;
  public static final int repetir = 48;
  public static final int comentario_linea = 8;
  public static final int fin_metodo = 52;
  public static final int dividido = 16;
  public static final int si = 33;
  public static final int mientras = 45;
  public static final int es_igual = 23;
  public static final int menor_o_igual = 22;
  public static final int fin_si = 34;
  public static final int menos = 13;
  public static final int menor = 20;
  public static final int fin_mientras = 47;
  public static final int EOF = 0;
  public static final int mas = 12;
  public static final int para = 40;
  public static final int verdadero = 2;
  public static final int fin_para = 42;
  public static final int error = 1;
  public static final int mayor = 19;
  public static final int metodo = 51;
  public static final int entero = 5;
  public static final int or = 25;
  public static final int incremental = 44;
  public static final int por = 15;
  public static final int funcion = 54;
  public static final int imprimir_nl = 58;
  public static final int potencia = 14;
  public static final int falso = 3;
  public static final int fin_segun = 39;
  public static final int segun = 37;
  public static final int hacer = 46;
  public static final int variable = 10;
  public static final int ingresar = 30;
  public static final int con_valor = 32;
  public static final int fin = 29;
  public static final int de_lo_contrario = 35;
  public static final int and = 26;
  public static final int not = 27;
  public static final int retornar = 50;
  public static final int o_si = 36;
  public static final int ejecutar = 56;
  public static final int decimal = 4;
  public static final int cadena = 6;
  public static final int boolean = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "verdadero",
  "falso",
  "decimal",
  "entero",
  "cadena",
  "caracter",
  "comentario_linea",
  "comentario_multilinea",
  "variable",
  "asignacionSimbolo",
  "mas",
  "menos",
  "potencia",
  "por",
  "dividido",
  "boolean",
  "mod",
  "mayor",
  "menor",
  "mayor_o_igual",
  "menor_o_igual",
  "es_igual",
  "es_diferente",
  "or",
  "and",
  "not",
  "inicio",
  "fin",
  "ingresar",
  "como",
  "con_valor",
  "si",
  "fin_si",
  "de_lo_contrario",
  "o_si",
  "segun",
  "entonces",
  "fin_segun",
  "para",
  "hasta",
  "fin_para",
  "con",
  "incremental",
  "mientras",
  "hacer",
  "fin_mientras",
  "repetir",
  "hasta_que",
  "retornar",
  "metodo",
  "fin_metodo",
  "con_parametros",
  "funcion",
  "fin_funcion",
  "ejecutar",
  "imprimir",
  "imprimir_nl"
  };
}

